### ISSUE TITLE
API Documentation link in Readme gives 404

### ISSUE THREAD

**Issue by DeepDiver1975** [InfiniteDevices/infinimesh#49]
**Describe the bug**
Link is wrong ....

**To Reproduce**
1. Go to 'https://infinimesh.github.io/infinimesh/swagger-ui/'
2. get 404

**Expected behavior**
well .. the docs ;-)

**Comment by DeepDiver1975** [comment]
There is another broken link in Readme: https://raw.githubusercontent.com/infinimesh/infinimesh/master/hack/microk8s/infinimesh-setup.sh ... should be infinimesh-setup-ubuntu.sh and/or infinimesh-setup-osx.sh ...

**Comment by slntopp** [comment]
We'll update the link, for now you can use  https://infinitedevices.github.io/infinimesh/ :)

![Screenshot 2020-07-20 at 15 40 27](https://user-images.githubusercontent.com/32666515/87944199-6026fc80-ca9f-11ea-8764-7048e3f68fa8.png)
